services:
    jenkins:
        build: ./jenkins-image
        container_name: jenkins
        restart: unless-stopped
        user: "0:0"
        ports:
            - "127.0.0.1:8080:8080"
            - "127.0.0.1:50000:50000"
        volumes:
            - jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    jenkins_home:
